Repository DeveloperAcademy-POSTECH/MC2-Team4-POMPOM, pull requests merged in 2022-07, with the labels that each got.

#81 [RECATOR]: Coupleview 리펙토링
  POMPOM/POMPOM.xcodeproj/project.pbxproj
  POMPOM/POMPOM/UI/CoupleView/CoupleView+Extensions.swift
  POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
  POMPOM/POMPOM/UI/CoupleView/ViewModel/CoupleViewModel.swift
Labels: 🛠리팩터링, 🔫 건

#86 [REFACTOR] ClothPickerViewModel, ClothViewModel -> Combine 코드 대체
  POMPOM/POMPOM/UI/ClothPickerView/ClothPickerView.swift
  POMPOM/POMPOM/UI/ClothPickerView/ClothPickerViewModel.swift
  POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
Labels: 🛠리팩터링, 🕺 루크, ⛓ Combine

#88 merge combine -> develop
  POMPOM/POMPOM.xcodeproj/project.pbxproj
  POMPOM/POMPOM.xcodeproj/xcuserdata/gongtae.xcuserdatad/xcschemes/xcschememanagement.plist
  POMPOM/POMPOM/UI/ClothPickerView/CategoryGrid.swift
  POMPOM/POMPOM/UI/ClothPickerView/ClothGrid.swift
  POMPOM/POMPOM/UI/ClothPickerView/ClothPickerView.swift
  POMPOM/POMPOM/UI/ClothPickerView/ClothPickerViewModel.swift
  POMPOM/POMPOM/UI/ClothPickerView/ColorGrid.swift
  POMPOM/POMPOM/UI/ClothPickerView/ViewModel/PickerViewModel.swift
  POMPOM/POMPOM/UI/CoupleView/ClothView.swift
  POMPOM/POMPOM/UI/CoupleView/ClothViewModel.swift
  POMPOM/POMPOM/UI/CoupleView/CoupleView+Extensions.swift
  POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
  POMPOM/POMPOM/UI/CoupleView/ViewModel/ClothesViewModel.swift
  POMPOM/POMPOM/UI/CoupleView/ViewModel/CoupleViewModel.swift
Labels: 🔫 건, 🕺 루크

#90 [REFACTOR] ClotheManager async await 으로 리팩터링
  POMPOM/POMPOM.xcodeproj/project.pbxproj
  POMPOM/POMPOM/Models/Cloth.swift
  POMPOM/POMPOM/Networking/ClothService.swift
  POMPOM/POMPOM/Networking/ClothesManager.swift
  POMPOM/POMPOM/Networking/CodeManager.swift
  POMPOM/POMPOM/UI/ClothPickerView/ClothPickerViewModel.swift
  POMPOM/POMPOM/UI/CoupleView/CoupleView+Extensions.swift
  POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
  POMPOM/POMPOM/UI/CoupleView/ViewModel/ClothesViewModel.swift
  POMPOM/POMPOM/UI/CoupleView/ViewModel/CoupleViewModel.swift
Labels: 🛠리팩터링, 🕺 루크, ⛓ async/await
